export default [
  {
    login: 'fobidlim',
    id: 7855177,
    node_id: 'MDQ6VXNlcjc4NTUxNzc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/7855177?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/fobidlim',
    html_url: 'https://github.com/fobidlim',
    followers_url: 'https://api.github.com/users/fobidlim/followers',
    following_url:
      'https://api.github.com/users/fobidlim/following{/other_user}',
    gists_url: 'https://api.github.com/users/fobidlim/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/fobidlim/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/fobidlim/subscriptions',
    organizations_url: 'https://api.github.com/users/fobidlim/orgs',
    repos_url: 'https://api.github.com/users/fobidlim/repos',
    events_url: 'https://api.github.com/users/fobidlim/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/fobidlim/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'goocci',
    id: 20539011,
    node_id: 'MDQ6VXNlcjIwNTM5MDEx',
    avatar_url: 'https://avatars.githubusercontent.com/u/20539011?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/goocci',
    html_url: 'https://github.com/goocci',
    followers_url: 'https://api.github.com/users/goocci/followers',
    following_url: 'https://api.github.com/users/goocci/following{/other_user}',
    gists_url: 'https://api.github.com/users/goocci/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/goocci/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/goocci/subscriptions',
    organizations_url: 'https://api.github.com/users/goocci/orgs',
    repos_url: 'https://api.github.com/users/goocci/repos',
    events_url: 'https://api.github.com/users/goocci/events{/privacy}',
    received_events_url: 'https://api.github.com/users/goocci/received_events',
    type: 'User',
    site_admin: false,
  },
  {
    login: 'jaero0725',
    id: 55049159,
    node_id: 'MDQ6VXNlcjU1MDQ5MTU5',
    avatar_url: 'https://avatars.githubusercontent.com/u/55049159?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jaero0725',
    html_url: 'https://github.com/jaero0725',
    followers_url: 'https://api.github.com/users/jaero0725/followers',
    following_url:
      'https://api.github.com/users/jaero0725/following{/other_user}',
    gists_url: 'https://api.github.com/users/jaero0725/gists{/gist_id}',
    starred_url:
      'https://api.github.com/users/jaero0725/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jaero0725/subscriptions',
    organizations_url: 'https://api.github.com/users/jaero0725/orgs',
    repos_url: 'https://api.github.com/users/jaero0725/repos',
    events_url: 'https://api.github.com/users/jaero0725/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/jaero0725/received_events',
    type: 'User',
    site_admin: false,
  },
];
