export default {
  login: 'limunosekai',
  id: 69956570,
  node_id: 'MDQ6VXNlcjY5OTU2NTcw',
  avatar_url: 'https://avatars.githubusercontent.com/u/69956570?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/limunosekai',
  html_url: 'https://github.com/limunosekai',
  followers_url: 'https://api.github.com/users/limunosekai/followers',
  following_url:
    'https://api.github.com/users/limunosekai/following{/other_user}',
  gists_url: 'https://api.github.com/users/limunosekai/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/limunosekai/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/limunosekai/subscriptions',
  organizations_url: 'https://api.github.com/users/limunosekai/orgs',
  repos_url: 'https://api.github.com/users/limunosekai/repos',
  events_url: 'https://api.github.com/users/limunosekai/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/limunosekai/received_events',
  type: 'User',
  site_admin: false,
  name: 'Henry, Lim (Seonghyeon)',
  company: 'home',
  blog: 'https://limunosekai.github.io/',
  location: 'Seoul, South Korea',
  email: null,
  hireable: true,
  bio: 'Web & Web App Developer. 　　　　　아직은 지망생입니다.',
  twitter_username: null,
  public_repos: 70,
  public_gists: 0,
  followers: 3,
  following: 7,
  created_at: '2020-08-20T06:55:50Z',
  updated_at: '2021-06-23T13:43:12Z',
};
